# Run generate-doc script.

# TODO: push on master shimming-toolbox
#trigger:

# use the self-hosted runner at tristano.neuro.polymtl.ca
# this has Matlab installed and a license to use it.
pool: 'Default'

steps:
- script: |
    # Beware: you MUST put `quit` at the end; Matlab does not auto-quit.
    # https://www.mathworks.com/matlabcentral/answers/523194-matlab-script-in-batch-from-unix-command-line
    matlab -nodisplay -nosplash -r "disp('Hello from Matlab'); quit"
  displayName: 'Generate-doc'
